[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Manav Penubaku <manav.prasad.27@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
